[package]
name = "Idris2-SystemsBiology-Wiki"
version = "0.1.0"
ipkg = "Idris2-SystemsBiology-Wiki.ipkg"

[custom.all.Idris2-Multiset-Core]
type = "local"
path = "../Idris2-Multiset-Core"
ipkg = "Idris2-Multiset-Core.ipkg"

[custom.all.Idris2-Multiset-Transform]
type = "local"
path = "../Idris2-Multiset-Transform"
ipkg = "Idris2-Multiset-Transform.ipkg"

[custom.all.Idris2-Multiset-Binary]
type = "local"
path = "../Idris2-Multiset-Binary"
ipkg = "Idris2-Multiset-Binary.ipkg"

[custom.all.Idris2-Geometry]
type = "local"
path = "../Idris2-Geometry"
ipkg = "Idris2-Geometry.ipkg"

[custom.all.Idris2-Physics]
type = "local"
path = "../Idris2-Physics"
ipkg = "Idris2-Physics.ipkg"

[custom.all.Idris2-Chemistry]
type = "local"
path = "../Idris2-Chemistry"
ipkg = "Idris2-Chemistry.ipkg"

[custom.all.Idris2-Biology]
type = "local"
path = "../Idris2-Biology"
ipkg = "Idris2-Biology.ipkg"

[custom.all.Idris2-Cosmos]
type = "local"
path = "../Idris2-Cosmos"
ipkg = "Idris2-Cosmos.ipkg"

[custom.all.idris2-Dihedron]
type = "local"
path = "../idris2-Dihedron"
ipkg = "idris2-Dihedron.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
